name: Bug report
description: File a bug/issue
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Package version
      description: Output of `composer show ovac/guardrails | head -n1`
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Please provide exact steps/code.
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP version
    validations:
      required: true
  - type: input
    id: laravel
    attributes:
      label: Laravel version
    validations:
      required: true

