name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the feature and problem it solves.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution ideas
      description: How would you implement this?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds?

