name: static-analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress

  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress
      - name: Laravel Pint
        run: ./vendor/bin/pint --test

